version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      main:
        applies-to: version-updates
        patterns:
          - "*"
      sec:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: golang.org/x/tools
      - dependency-name: google.golang.org/grpc
    groups:
      main:
        applies-to: version-updates
        patterns:
          - "*"
      sec:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: gomod
    directory: /tools
    schedule:
      interval: weekly
    ignore:
      - dependency-name: golang.org/x/tools
      - dependency-name: google.golang.org/grpc
    groups:
      main:
        applies-to: version-updates
        patterns:
          - "*"
      sec:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 0
    ignore:
      # These libs are updated by a Makefile command
      - dependency-name: github.com/aiven/go-client-codegen
      - dependency-name: github.com/aiven/go-api-schemas
