linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - revive # TODO: Configure according to https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md.
    - staticcheck
    - unconvert
    - unused
    - stylecheck

issues:
  exclude:
    # TODO: We can have a whitelist for revive's var-naming rule.
    - 'var-naming: .*'

    # TODO: We probably should add comments to all exported functions and methods.
    - 'exported: .*'
