linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - staticcheck
    - structcheck
    - unconvert
    - unused
    - varcheck

issues:
  exclude-use-default: false

run:
  go: '1.17' # See https://github.com/golangci/golangci-lint/issues/2649.
