dir: "mocks"
outpkg: "mocks"
with-expecter: True
issue-845-fix: True
resolve-type-alias: False
filename: "{{ .InterfaceName | lower }}.go"
packages:
  github.com/aiven/go-client-codegen:
    config:
    interfaces:
      Client:
