rules:
- id: outdated-copyright
  languages: [generic]
  patterns:
  - pattern: |
      Copyright (c) $Y Aiven, Helsinki, Finland. https://aiven.io/
  - metavariable-regex:
      metavariable: $Y
      regex: ^(?!2021)
  fix: |
      Copyright (c) 2021 Aiven, Helsinki, Finland. https://aiven.io/
  message: |
    Aiven copyright message is outdated
  severity: WARNING

- id: schema-resource without description
  languages: [go]
  paths:
    include:
    - "resource_*"
    - "datasource_*"
  patterns:
  - pattern: |
      &schema.Resource{ ... } 
  - pattern-not: |
      &schema.Resource{ ..., Description: ..., ... }
  - pattern-inside: |
      func $F() *schema.Resource { ... }

  message: |
    Each schema resource should have a description
  severity: WARNING

- id: schema-element without description
  languages: [go]
  paths:
    include:
    - "resource_*"
    - "datasource_*"
  patterns:
  - pattern-inside: |
      map[string]*schema.Schema{ ... }
  - pattern: |
      { ... }
  - pattern-not: |
      { ..., Description: ..., ... }
  message: |
    Each schema field should have a description
  severity: WARNING

