# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.21.2"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.9.0"

[[constraint]]
  name = "github.com/aiven/aiven-go-client"
  revision = "fafcf428b65b2a6a1fabf28cc9fc91a6915f358d"
  source = "github.com/aiven/aiven-go-client"

[prune]
  go-tests = true
  unused-packages = true
