name: acceptance tests

on:
  pull_request:
    branches:: [main]

jobs:
  acceptance-tests:
    runs-on: ubuntu-18.04

    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: make testacc
      env:
        AIVEN_TOKEN: ${{ secrets.AIVEN_TOKEN }}
        AIVEN_PROJECT_NAME: ${{ secrets.AIVEN_PROJECT_NAME }} 
