name: Acceptance Tests

on:
  issue_comment:
    types: [created]


concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger:
    runs-on: ubuntu-20.04
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/acceptance_tests'}}

    steps:
    - uses: actions/github-script@v5
      with:
        script: |
          const username = context.payload.sender.login;
          await github.rest.teams.getMembershipForUserInOrg({
            org: 'aiven',
            team_slug: 'aiven-terraform-reviewers',
            username: username,
          });

    - uses: actions/github-script@v5
      id: sha
      with:
        result-encoding: string
        script: |
          const { owner, repo, number } = context.issue;
          const pr = await github.rest.pulls.get({
            owner,
            repo,
            pull_number: number,
          });
          return pr.data.head.sha          

  acceptance_tests:
    needs: trigger
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.sha.outputs.result }}

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        same-branch-only: false

    - run: make testacc
      env:
        AIVEN_TOKEN: ${{ secrets.AIVEN_TOKEN }}
        AIVEN_PROJECT_NAME: ${{ secrets.AIVEN_PROJECT_NAME }} 

    - uses: nick-invision/retry@v2
      if: always()
      with:
        timeout_minutes: 10
        max_attempts: 10
        command: make sweep
      env:
        AIVEN_TOKEN: ${{ secrets.AIVEN_TOKEN }}
        AIVEN_PROJECT_NAME: ${{ secrets.AIVEN_PROJECT_NAME }}
