name: Acceptance Tests

on:
  pull_request:
    branches:: [master]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  acceptance-tests:
    runs-on: ubuntu-18.04

    steps:
    - name: Turnstyle
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        same-branch-only: false

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Acceptance Tests
      run: make testacc
      env:
        AIVEN_TOKEN: ${{ secrets.AIVEN_TOKEN }}
        AIVEN_PROJECT_NAME: ${{ secrets.AIVEN_PROJECT_NAME }} 

    - name: Cleanup Aiven Resources
      uses: nick-invision/retry@v2
      if: always()
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: make sweep
      env:
        AIVEN_TOKEN: ${{ secrets.AIVEN_TOKEN }}
        AIVEN_PROJECT_NAME: ${{ secrets.AIVEN_PROJECT_NAME }} 

