name: Changelog Check

on:
  pull_request_target:
    branches: [master, v*]


jobs:
  check_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: mwcodebase/versioning-checker@v2.2
        with:
          tracked_files: 'CHANGELOG.md'
