name: Changelog Enforcer

on:
  pull_request:
    branches:
      - main
      - v*
  push:
    branches:
      - main
      - release-*

permissions:
  contents: read

jobs:
  changelog-enforcer:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && !contains(github.event.pull_request.labels.*.name, 'no changelog')
    steps:
      - uses: dangoslen/changelog-enforcer@v3
