name: Changelog Check
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Check Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Changelog check
        uses: Zomzog/changelog-checker@v1.2.0
        with:
          fileName: CHANGELOG.md
          noChangelogLabel: 'skip-changelog'
          checkNotification: Detailed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

