name: Changelog Check

on:
  pull_request:
    branches: [master]


jobs:
  check_changelog:
    if: contains(github.event.pull_request.labels.*.name, 'needs-changelog')

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - uses: mwcodebase/versioning-checker@v2.2
        with:
          tracked_files: 'CHANGELOG.md'
