name: Changelog Enforcer

on:
  pull_request:
    branches:
      - main
      - v*

permissions:
  contents: read

jobs:
  changelog-enforcer:
    runs-on: ubuntu-latest
    steps:
      - uses: dangoslen/changelog-enforcer@v3
