name: Dependency Review

on:
  pull_request:
    branches:
      - main
      - v*
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

# TODO: This is currently not supported, see https://github.com/actions/dependency-review-action/issues/30.
#  push:
#    branches:
#      - main
#      - v*

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip workflows')) || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/dependency-review-action@v3
