name: Lint

on:
  push:
    branches: [ main, v* ]
  pull_request:
    branches: [ main, v* ]

permissions:
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1

  make_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - run: make lint

  check_docs_were_generated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - run: make docs
      - run: git diff --exit-code
