name: Lint

on:
  pull_request:
    branches:
      - main
      - v*
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
  push:
    branches:
      - main
      - v*

permissions:
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip workflows')) || github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3
    - uses: returntocorp/semgrep-action@v1

  make_lint:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip workflows')) || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - run: make lint

  check_docs_were_generated:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip workflows')) || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - run: make docs
      - run: git diff --exit-code
