name: Release Artifacts

on:
 push:
    tags: ['v*']

jobs:
  build_and_upload_artifacts:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - uses: hashicorp/ghaction-import-gpg@v2.1.0
      id: import_gpg
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}

    - uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
