name: Release Artifacts

on:
 push:
    tags:
      - v*

jobs:
  build_and_upload_artifacts:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - uses: crazy-max/ghaction-import-gpg@v5
      id: import_gpg
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}

    - uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --rm-dist
      env:
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
