name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  go_test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - uses: actions/checkout@v2
      with:
       fetch-depth: 0
    - run: make test
